### ISSUE TITLE
Licenciamiento data a usar y preguntas generales

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-2-preguntas-investigacion-lodurr#1]
Basados en la conversación en la que le externe mi deseo en estudiar los incendios forestales, he estado analizando la información basado en la data que produce la NASA sin embargo para obtenerla debo realizar un request, lo cual me confunde por que no he encontrado el tipo de licenciamiento de esta data y no se si pueda usarla para este proyecto. 
La pregunta sería si puedo usar la misma para el desarrollo del curso.
Abajo esta el link de descarga para mas información
https://firms.modaps.eosdis.nasa.gov/download/

Por otro lado mi idea es realizar un analisis temporal de los datos haciendo una interpolación respecto a las variables de temperatura, precipitacion, radiación solar y velocidad del viento de la fuente http://worldclim.org/version2 para de esta manera conocer cual es o son las areas mas propensas para incendios y en que periodo del año son mas y menos frecuentes los mismos. 
Para esta parte, tendría unas preguntas.
 1. Que periodo debería descargar para obtener una información confiable?
 2. Es correcto lo que estoy planteando para el desarrollo del curso?
 3. Es muy ambicioso o por el contrario muy básico este tipo de trabajo para el desarrollo del mismo.

Agradezco su ayuda y orientación.

**Comment by lodurr** [comment]
Analizando la data de **worldclim** veo que la misma solo esta hasta el año 2000 por lo que no se si esto desfasaría el proyecto, Sin embargo creo que este tipo de data es mas facil de conseguir, Estaré informando por este medio cualquien hallazgo.

**Comment by geofis** [comment]
Bueno, no estoy seguro sobre el licenciamiento, pero hasta donde entiendo, pienso que no habría inconvenientes.

Aunque los puntos MODIS son generalmente más recientes (>2000) que el período analizado en worldclim (<2000), este último sirve como marco de referencia, es decir, marca la base de la distribución espacial de un conjunto de variables. Alguna relación debe haber entre dicho marco de referencia de worldclim y la localización de los puntos de calor/fuegos de MODIS, aun cuando ambos son asíncronos. 

En tu caso, si localizas los puntos de calor sobre el mapa y analizas patrones espaciales, seguramente surgirá un patrón agregado desde donde se podrán extraer *hot spots* (claro, *hot spots* en el sentido LISA, no en el sentido MODIS). Dicho patrón es probable que presente asociación estadística con variables de terreno que te resultarán relativamente fáciles de conseguir, como elevación, pendiente, cobertura arbórea, tipo de bosque, proximidad a áreas de cultivo, variables de worldclim (aun siendo asíncrono), y otras que podrías evaluar. De esta manera, como ves, serían varias las preguntas de análisis espacial que te podrías plantear.

Puedes pasar tus preguntas al repo y las podemos seguir discutiendo allí.
